<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reMaVeh" nsURI="http://www.example.org/reMaVeh" nsPrefix="reMaVeh">
  <eClassifiers xsi:type="ecore:EClass" name="Aceite" eSuperTypes="#//TargetMantenimiento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ViscosidadSAEBajaTemperatura"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ViscosidadSAEAltaTemperatura"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repuesto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CodigoIdentificador" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Marca" lowerBound="1" eType="#//Marca"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PeriodicidadesMantenimiento"
        upperBound="-1" eType="#//PeriodicidadMantenimiento" eOpposite="#//PeriodicidadMantenimiento/Repuesto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Kits" upperBound="-1" eType="#//Kit"
        eOpposite="#//Kit/Repuestos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TargetMantenimiento" lowerBound="1"
        eType="#//TargetMantenimiento"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Automovil" eSuperTypes="#//Vehiculo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Patente" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumeroChasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CodigoColorPintura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Combustible">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tipo" lowerBound="1" eType="#//TipoCombustible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Costo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Monto" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moneda" lowerBound="1"
        eType="#//Moneda"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquipamientoAirbags">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Volante" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Guantera" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DelanteroIzquierdo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DelanteroDerecho" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TraseroIzquierdo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TraseroDerecho" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fluido" eSuperTypes="#//TargetMantenimiento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Repuestos" lowerBound="1"
        upperBound="-1" eType="#//Repuesto" eOpposite="#//Repuesto/Kits"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mantenimiento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Accion" ordered="false"
        unique="false" eType="#//EAccionMantenimiento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Repuesto" lowerBound="1"
        eType="#//Repuesto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mecanico" lowerBound="1"
        eType="#//Reparador"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServicioMecanico" lowerBound="1"
        eType="#//ServicioMecanico" eOpposite="#//ServicioMecanico/Mantenimientos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Costo" lowerBound="1" eType="#//Costo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marca">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModeloVehiculo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Version" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GrupoModelo" lowerBound="1"
        eType="#//GrupoModelo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CombustibleRecomendado"
        eType="#//Combustible"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Airbags" eType="#//EquipamientoAirbags"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AceiteRecomendado" eType="#//Aceite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RepuestosRecomendados"
        upperBound="-1" eType="#//Repuesto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PresionesNeumaticos" upperBound="-1"
        eType="#//PresionNeumaticos" eOpposite="#//PresionNeumaticos/ModeloVehiculo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Moneda">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TiposCambio" upperBound="-1"
        eType="#//TipoCambio" eOpposite="#//TipoCambio/Moneda"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicidadMantenimiento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kilometros" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dias" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Meses" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Anios" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Repuesto" eType="#//Repuesto"
        eOpposite="#//Repuesto/PeriodicidadesMantenimiento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModeloVehiculo" eType="#//ModeloVehiculo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EsDefault" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pieza" eSuperTypes="#//TargetMantenimiento">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Ubicacion" eType="#//UbicacionPieza"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServicioMecanico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FechaInicio" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FechaFin" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EntidadReparadora" lowerBound="1"
        eType="#//EntidadReparadora" eOpposite="#//EntidadReparadora/ServiciosMecanicos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vehiculo" lowerBound="1"
        eType="#//Vehiculo" eOpposite="#//Vehiculo/ServiciosMecanicos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Mantenimientos" upperBound="-1"
        eType="#//Mantenimiento" eOpposite="#//Mantenimiento/ServicioMecanico"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="KilometrajeVehiculo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CostoManoObra" lowerBound="1"
        eType="#//Costo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntidadReparadora">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiciosMecanicos" upperBound="-1"
        eType="#//ServicioMecanico" eOpposite="#//ServicioMecanico/EntidadReparadora"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Direccion" lowerBound="1"
        eType="#//Direccion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reparadores" upperBound="-1"
        eType="#//Reparador" eOpposite="#//Reparador/EntidadesReparadoras"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoEntidad" lowerBound="1"
        eType="#//TipoEntidadReparadora"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UbicacionPieza">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Izquierda" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Derecha" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Superior" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Inferior" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vehiculos" upperBound="-1"
        eType="#//Vehiculo" eOpposite="#//Vehiculo/Usuario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehiculo" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modelo" lowerBound="1"
        eType="#//ModeloVehiculo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kilometraje" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Usuario" lowerBound="1"
        eType="#//Usuario" eOpposite="#//Usuario/Vehiculos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AnioFabricacion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiciosMecanicos" upperBound="-1"
        eType="#//ServicioMecanico" eOpposite="#//ServicioMecanico/Vehiculo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EAccionMantenimiento">
    <eLiterals name="Reparacion"/>
    <eLiterals name="Reemplazo" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetMantenimiento" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrupoModelo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Marca" lowerBound="1" eType="#//Marca"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Direccion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Calle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumeroCalle" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPA" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Localidad" lowerBound="1"
        eType="#//Localidad"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Localidad">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Partido" lowerBound="1"
        eType="#//Partido" eOpposite="#//Partido/Localidades"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partido">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provincia" lowerBound="1"
        eType="#//Provincia" eOpposite="#//Provincia/Partidos"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Localidades" upperBound="-1"
        eType="#//Localidad" eOpposite="#//Localidad/Partido"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Provincia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Pais" lowerBound="1" eType="#//Pais"
        eOpposite="#//Pais/Provincias"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Partidos" upperBound="-1"
        eType="#//Partido" eOpposite="#//Partido/Provincia"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pais">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Provincias" upperBound="-1"
        eType="#//Provincia" eOpposite="#//Provincia/Pais"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persona" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Apellido" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumeroDocumento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoDocumento" lowerBound="1"
        eType="#//TipoDocumento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Telefonos" upperBound="-1"
        eType="#//Telefono" eOpposite="#//Telefono/Persona"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDocumento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reparador" eSuperTypes="#//Persona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EntidadesReparadoras" upperBound="-1"
        eType="#//EntidadReparadora" eOpposite="#//EntidadReparadora/Reparadores"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoCombustible">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Telefono">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Numero" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TipoTelefono" lowerBound="1"
        eType="#//TipoTelefono"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Persona" lowerBound="1"
        eType="#//Persona" eOpposite="#//Persona/Telefonos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoTelefono">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PresionNeumaticos">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Neumatico" lowerBound="1"
        eType="#//Neumatico"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModeloVehiculo" lowerBound="1"
        eType="#//ModeloVehiculo" eOpposite="#//ModeloVehiculo/PresionesNeumaticos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RuedaDelantera" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RuedaTrasera" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Neumatico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Modelo" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Talon" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rodado" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ancho" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Marca" lowerBound="1" eType="#//Marca"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoEntidadReparadora">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoCambio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moneda" lowerBound="1"
        eType="#//Moneda" eOpposite="#//Moneda/TiposCambio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Valor" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fecha" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
